replicaCount: 1

image:
  repository: ghcr.io/lucchmielowski/diiage-finals/traffic-gen
  tag: "latest"
  pullPolicy: IfNotPresent

env:
  BACKEND_URL: "http://backend-prod:80"
  INTERVAL: "5s"

resources:
  limits:
    cpu: 50m
    memory: 64Mi
  requests:
    cpu: 10m
    memory: 32Mi
