apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "traffic-gen.fullname" . }}
  labels:
    {{- include "traffic-gen.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "traffic-gen.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "traffic-gen.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: traffic-gen
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
