apiVersion: v1
kind: Service
metadata:
  name: {{ include "diiage-finals-app.fullname" . }}-backend
  labels:
    {{- include "diiage-finals-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.backend.type }}
  selector:
    app: {{ include "diiage-finals-app.name" . }}-backend
  ports:
    - name: http
      port: {{ .Values.service.backend.port }}
      targetPort: 8080
      protocol: TCP
