apiVersion: v2
name: monitoring-stack
description: Monitoring stack chart bundling Prometheus, Grafana, Tempo, and OpenTelemetry Collector
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: prometheus
    version: 28.6.0
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus.enabled
  
  - name: grafana
    version: 10.5.13
    repository: https://grafana.github.io/helm-charts
    condition: grafana.enabled
  
  - name: tempo
    version: 1.24.3
    repository: https://grafana.github.io/helm-charts
    condition: tempo.enabled
  
  - name: opentelemetry-operator
    version: 0.102.0
    repository: https://open-telemetry.github.io/opentelemetry-helm-charts
    condition: opentelemetry-operator.enabled
