apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "diiage-finals-app.fullname" . }}-backend-config
data:
  APP_NAME: {{ .Values.backend.config.appName | quote }}
  LOG_LEVEL: {{ .Values.backend.config.logLevel | quote }}
