apiVersion: v1
kind: Service
metadata:
  name: {{ include "diiage-finals-app.fullname" . }}-redis
  labels:
    {{- include "diiage-finals-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.redis.type }}
  selector:
    app: {{ include "diiage-finals-app.name" . }}-redis
  ports:
    - name: redis
      port: {{ .Values.service.redis.port }}
      targetPort: 6379
      protocol: TCP
